### ISSUE TITLE
Renaming directory fails

### ISSUE THREAD

**Issue by tetianakh** [kahing/goofys#109]
First of all, thanks a lot for the great project. I'm just starting using it, but I already like it very much.

I've noticed that renaming directories doesn't work:
```
$ mkdir /mnt/bucket/foo
$ touch /mnt/bucket/foo/1.txt
$ mv /mnt/bucket/foo /mnt/bucket/bar
mv: cannot move ‘/mnt/bucket/foo’ to ‘/mnt/bucket/bar’: Directory not empty
```
Am I missing something? Is there any chance to make it work?

**Comment by kahing** [comment]
this problem happens when you rename a non-empty directory. renaming empty directories work.

I am hesitant to support renaming non-empty directory because as you probably know, S3 doesn't have rename operations, and goofys currently emulate renaming a file by doing a server-side copy to the new name, and then delete the old one. The failure modes are relatively straight-forward, either nothing is done, or you have both the new and old file, which is rare (that means either goofys crashed and couldn't send out the delete, or delete somehow failed).

For renaming non-empty directories though, any failure server side copy of any of the file would result in failure. That's a much larger window of failure with more combinations of final state, and that's before considering possible race conditions (what if files are added to the directory during the rename?) I would really rather not do that.

Is this something you can work around on the application side?

**Comment by kahing** [comment]
closing, not going to support for now
