### ISSUE TITLE
minio support

### ISSUE THREAD

**Issue by atomi** [kahing/goofys#110]
is minio support planned? I noticed a test case for minio endpoint, but I checked and goofys requests buckets using subdomains which minio doesnt support.

**Comment by k0nsl** [comment]
I was just about to ticket in about this! It would be great if support for Minio could be implemented.

**Comment by kahing** [comment]
minio was removed from the tests because at the time it didn't support object overwrites and deletes. Reading https://github.com/minio/minio/issues/150 it's a little confusing as to whether it's supported now or not. Perhaps you guys know about this more than I do?

Just curious, how are you guys planning to use goofys with minio?

**Comment by atomi** [comment]
I have a lot of pdf documents that I sometimes share using Minio. I'd rather just delete my local copies and mount a minio bucket to upload/delete. I also do daily backups of everything in minio to b2 using rclone. @kahing checkout https://gitter.im/minio/minio if you have a question the lead devs will usually reply instantly.

**Comment by kahing** [comment]
rclone mount is interesting, thanks for the pointer. And you definitely won the blob store nerd award by mentioning two obscure blob stores in one sentence.

**Comment by kahing** [comment]
the above commit is about as much I am going to do for now. minio changes a lot and I don't have time to monitor its progress. feel free to ping me when there are exciting updates on minio land

**Comment by kahing** [comment]
closing, the rest of minio support will come when they are more S3 compatible
