### ISSUE TITLE
What is the minimal IAM policy?

### ISSUE THREAD

**Issue by rektide** [kahing/goofys#136]
What is the minimal IAM policy that Goofys needs to run?

I grepped around through source and this policy document example is what I've ended up with based on that- I'll update this post as soon as I get this new instance into prod & test it for a bit, confirm/deny-

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "Stmt1234567890000",
            "Effect": "Allow",
            "Action": [
                "s3:AbortMultipartUpload",
                "s3:DeleteObject",
                "s3:GetObject",
                "s3:ListBucket",
                "s3:ListBucketMultipartUploads",
                "s3:ListMultipartUploadParts",
                "s3:PutObject"
            ],
            "Resource": [
                "arn:aws:s3:::goofys-share-1",
                "arn:aws:s3:::goofys-share-2"
            ]
        }
    ]
}
```

**Comment by monken** [comment]
Your resource should include the objects in the bucket as well for operations based on keys such as GetObject:

```
"Resource": [
                "arn:aws:s3:::goofys-share-1", "arn:aws:s3:::goofys-share-1/*",
                "arn:aws:s3:::goofys-share-2", "arn:aws:s3:::goofys-share-2/*"
            ]
```

**Comment by kahing** [comment]
most of the permissions are not strictly speaking required. For example if you never delete files then you don't need DeleteObject, or if you only read then you don't need PutObject. AbortMultipartUpload is also not needed if you don't care about cleaning up failed multipart uploads (which should never happen anyway because goofys never crashes, right??)
