### ISSUE TITLE
Binary exits before filesystem mount

### ISSUE THREAD

**Issue by laurentb75** [kahing/goofys#140]
When trying to use goofys in a bash script, the command returns before the filesystem is actually mounted :

> #!/bin/bash
> goofys bucket /mnt/test
> touch /mnt/test/foo

In this example, goofys returns before filesystem is mounted so foo file is created on the local filesystem (Which as a side-effect prevents the mount because the folder is not empty anymore).
Used a sleep as a workaround but would like to avoid that.
Am I missing something ? Not a Go expert but i guess it should be synchronous instead of async ?

**Comment by kahing** [comment]
unfortunately that's not trivial to do, since the way to daemonize a program in golang is typically done by executing a copy of yourself instead of fork()

I see 2 ways to fix this:
 * use a named pipe, seems a bit overkill though just for the initial status
 * modify https://github.com/sevlyar/go-daemon to setup a pipe between parent/child (possibly involve making `daemon.Context.Reborn()` return a channel that hooks to the child's stdin.

**Comment by laurentb75** [comment]
Thanks a lot for the insight. Will have to stick with the sleep for now ...

**Comment by kahing** [comment]
hacked around this for now with some signal magic. if there's an error you still have to look at syslog to see what the error is, but at least the exit value is correct
