### ISSUE TITLE
Cannot create folder/files in mounted s3 bucket

### ISSUE THREAD

**Issue by raztud** [kahing/goofys#165]
Not sure if it is an issue or I do something wrong. 

I am logged in as a normal user (raztud), and I mount the s3 bucket like this:

```
goofys --region eu-west-1 bucketname /home/raztud/mywebsite.org/public_html/wp-content/s3
```
and it seems all the permissions are okay and I can browse through files.

```
# ls -lh ~/mywebsite.org/public_html/wp-content
...
drwxr-xr-x 2 raztud raztud 4.0K Mar 20 08:22 s3
...
# ls  -l s3/photos/mypics/DSC09463.JPG
-rw-r--r-- 1 raztud raztud 85614 Jul 14  2011 s3/photos/mypics/DSC09463.JPG
```

But:
1. I cannot create anything inside the s3 folder
```
# mkdir s3/asd
mkdir: cannot create directory ‘s3/asd’: Permission denied
# touch s3/blah
touch: failed to close 's3/blah': Permission denied
```

2. nginx cannot access the files:
```
# curl -I http://mywebsite.org/wp-content/s3/photos/mypics/DSC09463.JPG
HTTP/1.1 404 Not Found
```
and the nginx log:
```
2017/03/20 08:27:33 [error] 7733#7733: *3126 open() "/home/raztud/mywebsite.org/public_html/wp-content/s3/photos/mypics/DSC09463.JPG" failed (13: Permission denied), client: 5.104.159.12, server: mywebsite.org, request: "GET /wp-content/s3/photos/mypics/DSC09463.JPG HTTP/1.1", host: "mywebsite.org"
```

There is any trick how can I mount the bucket to be able to access the files from nginx and create files/folders inside the bucket?

Thx.

**Comment by kahing** [comment]
If the bucket is public-read, goofys by default uses that instead of the configured credential. To overwrite that, use --profile default (or replace default with the correct profile).

Is nginx running under the user raztud? If not, you need to use -o allow_other and possibly --file-mode/dir-mode options

**Comment by nohe427** [comment]
I am running into the same issue.  I tried --profile default with no success

**Comment by kahing** [comment]
could you post the output of --debug_s3?

**Comment by mrapczynski** [comment]
@raztud I am trying goofys for the first time, and I had the same problem. My issue was the IAM role for the VM I was using was too restrictive. If you are using IAM to guard S3, then try looking in your policies to see if that is where the denial is coming from.

**Comment by kahing** [comment]
closing for now, please reopen if the solution by @mrapczynski doesn't work

**Comment by dlhoward** [comment]
I am having the same issue and I am not running in a VM.  I am using MacOS with homebrew.  When I try and create a directory I get 
iosbuild$ mkdir folder1
mkdir: folder1: Input/output error

Syslog contains
/usr/local/Cellar/goofys/0.0.9/bin/goofys[99199]: s3.ERROR code=A header you provided implies functionality that is not implemented msg=501 request=

I have a feeling that it has to do with the content length being 0, because the same thing occurs if I try and 'touch' a file.  Yet I can copy files.
iosbuild$ touch file2
touch: file2: Input/output error

**Comment by andrewgaul** [comment]
@dlhoward Please run again and attach output from `--debug_s3`.

**Comment by kahing** [comment]
@dlhoward you are using go1.8 and no released version of goofys is compatible with it. Build from source in master

**Comment by shadiakiki1986** [comment]
Just my 2 cents:

Using [goofys](https://github.com/kahing/goofys/) to mount an s3 bucket in my ubuntu server filesystem via an IAM user attached to a similar policy to
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": "s3:*",
      "Resource": "example"   <<< replace example with ARN
    }
  ]
}
```
That caused the inability to create files.
Changing it to the `managed policy` of `AmazonS3FullAccess` works. I guess something wrong with my policy. Possible related issue I had noted earlier [here](https://stackoverflow.com/a/37532132/4126114)

**Comment by kahing** [comment]
I am confused, could you give a more concrete example? If you only allow access to "example", what files do you expect to be able to create?

**Comment by shadiakiki1986** [comment]
I mean that when I mounted an s3 bucket with goofys, I got an error about being unable to create files/folders. It turned out not to be because of goofys nor because of local file permissions, but because of the policy attached to the IAM user that I was using. The policy that did not work was my custom policy listed above. Replacing the policy with the one readily available from amazon (s3 full access) solved the problem.

**Comment by kahing** [comment]
Did the error come about when you mount or when you ran other commands?

**Comment by shadiakiki1986** [comment]
It came about after I mount when I tried `cp test.txt /mnt/my-s3/`

**Comment by kahing** [comment]
can you paste a more realistic example of "example"? Are you only allowing access to a path or is it a wildcard? See https://github.com/kahing/goofys/issues/136 for an example of a working policy

**Comment by shadiakiki1986** [comment]
My exact "example" was "arn:aws:s3:::shadi-torrents", where "shadi-torrents" was the name of the bucket. I don't specify neither path nor wildcard.
