### ISSUE TITLE
Question: Limits on parallel/simultaneous mounts

### ISSUE THREAD

**Issue by VinayaSathyanarayana** [kahing/goofys#174]
Is there a limit of how many Linux systems can mount the same bucket of S3 simultaneously.
Can I mount one bucket of S3 in about 1000 Linux Systems simultaneously?

**Comment by VinayaSathyanarayana** [comment]
@kahing - Your views please.

**Comment by kahing** [comment]
First of all there's no need to ping me just a day after you open the issue. It's quite rude actually since I am doing this in my own free time.

Second, there's no inherit limit in how many systems can mount a bucket at the same time. However, goofys is not a shared filesystem. There's no locking or any kind of kind of shared semantic beyond those offered by S3. There are also caveats of eventual consistency.

The short answer is if you are using this for read-only it works fine, and many people do this already with 100s of systems. If you have multiple writers writing the same files, then you will have to think about this more carefully if goofys (or even S3) is really what you want

**Comment by VinayaSathyanarayana** [comment]
Thanks for your answer.
My apologies for pinging you.
