### ISSUE TITLE
Please offer a way to limit memory usage

### ISSUE THREAD

**Issue by AndydeCleyre** [kahing/goofys#184]
I'm having trouble on some servers that need to mount a network drive (or s3 bucket) that's currently got ~1 TB of data, and growing. Some of the servers have broken the connection, and a server which still has the connection is teetering at the edge of OOM with ~2300M resident memory just for that goofys process.

No matter how slow the "filey" system were to get, limiting the memory used would be *infinitely* better than the mount just disappearing, and then potentially ending up plopping a bunch of orphaned files into the suddenly empty mountpoint directories across many different servers.

`goofys -v` reports `0.0.10` but I'm pretty sure it's `0.0.11`.

**Comment by AndydeCleyre** [comment]
Oh, I should note that the mounted filey system is not being used *at all*. It's mounted in anticipation of a future (though unless this changes, maybe not) swap. The bucket is being written to via rclone, separately, but the goofys process shouldn't be actively reading or writing a single thing.

**Comment by andrewgaul** [comment]
@AndydeCleyre Can you run goofys with debug logging and report the available, allocated, and buffers log lines (the ones in `internal/buffer_pool.go`)?  Also how much memory does your instance have?  goofys should use any available memory but return it during memory pressure or on idle.  Agree that a maximum would still be good.

**Comment by kahing** [comment]
to clarify, goofys would use up to 50% of the available memory when necessary. It periodically re-sample the amount of available memory so this shouldn't be causing a real problem. Please reopen if you can demonstrate otherwise.

**Comment by AndydeCleyre** [comment]
I'm sorry, it wasn't sufficiently convenient or free for me to intentionally recreate the problem for debugging.

**Comment by stevebma** [comment]
Hi @kahing 
I'm mounting 2 separate buckets (and so 2 goofys processes are launched via fstab), would this mean that _both_ will go up to 50%?

I'm asking this because I'm still running out of memory on quite a few occasions (v0.18 fixes have helped, but like @AndydeCleyre I'm still losing the mountpoint, which is a drag for my application).

Adding swap space has improved things quite a bit, but I would really like to explicitly limit memory usage by goofys. Would that be possible somehow? many thanks

**Comment by kahing** [comment]
Could you describe your workload more?

**Comment by stevebma** [comment]
The specific workload varies per server, but in general the OOM occurs when two goofys processes (running simultaneously) are competing for memory with some other processes (not something extremely demanding, but e.g. a webserver with some workers with fairly consistent memory usage)

e.g. PID / name / mem % 

[PID1]  goofys fstab#bucket1 (30% varies a lot)
[PID2]  goofys fstab#bucket2 (25% varies a lot)
[PID2] webserver (5%)
[PID4] workerA (5%)
[PID5] workerB (5%)
[PID6] workerC (5%)
[PID7] workerD (5%)
(.. other small stuff)

I also have some deployments where goofys is the only "demanding" process, in which case all is fine. My instances have at least 2GB mem.

**Comment by stevebma** [comment]
For clarity: the process is killed by the kernel, from a log:

```
kernel: [106623.291028] Out of memory: Kill process 2507 (goofys) score 463 or sacrifice child
kernel: [106623.295079] Killed process 2507 (goofys) total-vm:1186464kB, anon-rss:976272kB, file-rss:0kB, shmem-rss:0kB
```

**Comment by kahing** [comment]
Are you doing a lot of write/read? There are lots of ways goofys can use memory and there's no general way to limit memory usage. The one we have most obvious control over is the amount of write buffer to use. That we do attempt to auto-tune and it's possible that it's not optimal.

**Comment by stevebma** [comment]
This issue also occurs on systems that only read buckets (never write), so I don't think the write-buffer is the real problem here. Sure I'm doing reads/writes, but I wouldn't describe it as excessive.

The 50% limit that you described earlier, would it be possible to reduce that?
e.g. a  --memory_usage_limit=40% option would likely help my case.
This wouldn't have to impose a strict / fixed amount of memory

**Comment by RudraNirvan** [comment]
@kahing , regarding your comment "The one we have most obvious control over is the amount of write buffer to use.". How can this parameter be controlled? I don't see something akin to this under FlagStorage.
