### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by fmunteanu** [kahing/goofys#226]
Hi,

I have a bucket with 20 million images. Using goofys-0.017 and doing a simple `ls` takes bout 3-5 seconds for the first time:
```
$ time ls -lah /var/www/media/1000000/10000/100/10/100_1000.jpg
-rw-r--r--. 1 root root 5.2M Mar 18  2017 /var/www/media/1000000/10000/100/10/100_1000.jpg
real	0m4.930s
user	0m0.001s
sys	0m0.001s
```
My goal is to have these images served super fast with Nginx. My `/etc/fstab`:
```
goofys#mediasource  /var/www  fuse  _netdev,allow_other,--cheap  0 0
```
I used the `--cheap` option to stop the frequent API calls and save costs. Even without this option, the speed is VERY slow, on initial call. it makes sense, but how to a speed it up? I add new images into bucket, once or twice a day.

**Comment by kahing** [comment]
The issue is the number of nested directories, not number of images. To access `media/1000000/10000/100/10/100_1000.jpg`, fuse would have figure out that each component of the path is a directory. So the best we can do is 6 lookups. If you use `--cheap`, that could be 11-16 serial calls. If that's the case I wouldn't be surprised if it takes 3-5 seconds.

If you never need to do readdir, the best thing to do is reduce the number of nested directories. Setting `--stat-cache-ttl` and `--type-cache-ttl` to a high value can also help with subsequent lookups.

**Comment by fmunteanu** [comment]
Thanks for taking the time to explain. I plan to import the files to a new bucket, with the following structure:
```
$ ls -lah /usr/share/nginx/html/[goofys mount]
total 8.0K
drwxr-xr-x. 2 root root 4.0K Sep 30 00:08 .
drwxr-xr-x. 3 root root   98 Sep 30 00:01 ..
drwxr-xr-x. 2 root root 4.0K Sep 30 00:08 01
drwxr-xr-x. 2 root root 4.0K Sep 30 00:08 02
drwxr-xr-x. 2 root root 4.0K Sep 30 00:08 03
....
$ ls -lah /usr/share/nginx/html/[goofys mount]/01
total 281K
drwxr-xr-x. 2 root root 4.0K Sep 30 00:08 .
drwxr-xr-x. 2 root root 4.0K Sep 30 00:08 ..
-rw-r--r--. 1 root root 273K Sep 29 23:46 image.jpg
```
In other words, I will have only _one level_ of nested directories (01, 02, 03, up to 20). Inside each nested directory, I will have approximately _one million_ uniquely named images.

What options do you recommend for maximum performance? I currently use a `c4.2xlarge` EC2 instance to mount the bucket, with the following `/etc/fstab` line:
```
goofys#bucket  /usr/share/nginx/html/bucket  fuse  _netdev,allow_other,--cheap,--no-implicit-dir        0 0
```
Thank you for your support.

Regards,

Floren

**Comment by kahing** [comment]
well, `--cheap` is the opposite of performance :-P but since there's only one level of directory it shouldn't be too bad. Using large values of `--stat-cache-ttl` and `--type-cache-ttl` will also help.

Also, make sure that you will never do ls in the directories (either explicitly or through directory indexes through your web server), because listing a million files is inherently slow.

**Comment by fmunteanu** [comment]
I'll remove the `--cheap` option, then. What is the proper format for the `--stat-cache-ttl` setting, for example (default: 1m0s)? Can I use this format: `1d2h3m0s` or dies it have to be specific to minutes and seconds only: `2000m0s`. From your experience, what would be a good value for the settings? I'm thinking to set them to one hour, so indexes will be refreshed every hour.
