### ISSUE TITLE
Goofys does not show mtime for folders

### ISSUE THREAD

**Issue by EssentialMix** [kahing/goofys#249]
I see that we have mtime for files, but not for folders.
Is this is expected behavior? Do you plan to implement this?

**Comment by kahing** [comment]
we do _show_ mtime for folders which we derive from files that we have seen, or we show a dummy time (time of mount). We don't, however, _store_ the mtime. I can consider a PR that does that. Said PR should consider what happens if multiple files are created under the dir at once and not repeatedly update the mtime of the parent dir.

**Comment by EssentialMix** [comment]
Ok i probably need to clarify we are using GCS for backend, dont know if this change things. But we all time see dummy time (time of mount) instead of files time or something else. How you actually looking time if you dont go inside folder? I guess s3fs storing mtime inside metadata of object.

**Comment by kahing** [comment]
we show the greatest mtime of the files inside the directory if you've done a `ls`. If not ya right now it's not very smart. We do (well GCS/S3 does) record the time the directory blob is updated if you did `mkdir` through goofys, but we don't seem to use it (an oversight). Obviously if they are implicit directories then there's no object to record the mtime.

How are you trying to use mtime of directories? Is it sufficient for it to have the time of `mkdir` or do you actually want it to be updated as new files are created?

**Comment by EssentialMix** [comment]
Yes, it will be enough, we just creating builds and want to see dates of this builds. We doing some tricky part to have symlinks, we creating all objects using s3fs and using goofys for showing objects to user. I dont know if goofys rely on s3fs metadata. But thanks for you help here.

**Comment by kahing** [comment]
Ok I've done as much as I want to do for now. Note that dir mtime is _best effort_. For example, if you have `dir1/dir2/`, and you `ls dir1`, subsequent `ls -ld dir1/dir2` will _not_ return the correct mtime, because when we readdir `dir1` we slurped up `dir1/dir2` as a common prefix, so we won't see the mtime on the directory blob.

You can force goofys to lookup the directory blob again with `--stat-cache-ttl 0 --type-cache-ttl 0` with the performance caveats.

Similarly, because we look up directory in paralle, when you do `ls -ld dir3/`, it's possible that the LIST lookup will come back first and so we won't see the dir mtime. To workaround that, either use `--cheap` or `--no-implicit-dir`.

**Comment by kahing** [comment]
Also, goofys does not read s3fs' metadata
