### ISSUE TITLE
rsync cannot track the changes on goofys mounted S3

### ISSUE THREAD

**Issue by fldhmily633190808** [kahing/goofys#251]
Hi,

# Question 1:  RSYNC cannot track the changes on goofys mounted  S3, is this an expected behaviour ?
As we want to migrate the data from EFS to S3, but we might not be able to shut down the application and wait for the entire EFS to finish the copy to S3, therefore, we might be doing the initial rsync first then do the subsequent incremental rsync.

I have around 830MB files in EFS (/mnt/efsnfs) for proof of concept testing, and I have done the 1st rsync. 
I also have another directory to do the initial rsync (from /mnt/efsnfs to /mnt/ec2nfs)

## 1st I deleted abc.sh file on /mnt/efsnfs

[root@ip-10-86-13-161 mnt]# rm ./efsnfs/abc.sh 
rm: remove regular empty file ‘./efsnfs/abc.sh’? y

## 2nd  I did the update rsync to the NFS
[root@ip-10-86-13-161 mnt]# rsync -a -v -r /mnt/efsnfs/ /mnt/ec2nfs/
sending incremental file list
./
data/xnat/home/work/cache/nrg.data
data/xnat/home/work/cache/org%002ehibernate%002ecache%002einternal%002e%0053tandard%0051uery%0043ache.data

sent 389209 bytes  received 592 bytes  41031.68 bytes/sec
total size is 817026110  speedup is 2096.01

## 3rd However, when I did the rsync on the Goofys, it did an initial rsync again.
[root@ip-10-86-13-161 mnt]# rsync -a -v -r /mnt/efsnfs/ /mnt/S3dev/
sending incremental file list
./
data/
data/xnat/
data/xnat/archive/
data/xnat/archive/test011/
data/xnat/archive/test011/arc001/
data/xnat/archive/test011/arc001/abc_MR1/
data/xnat/archive/test011/arc001/abc_MR1/dcmtoxnat.log
data/xnat/archive/test011/arc001/abc_MR1/SCANS/

# Questions 2: Even for the initial rsync there are some performance differences. Is the performance look like normal ?
Note: I am running this at t2.medium in ap-southeast-2, i mounted specifying the region, where the S3 bucket sits. 
goofys --debug_fuse --debug_s3  —region ap-southeast-2 BUCKETNAME /mnt/S3dev/

Rsync: 
## 1st from EFS to S3

time rsync -a -v -r /mnt/efsnfs/ /mnt/S3dev/
sent 817326082 bytes  received 57187 bytes  1,076,212.34 bytes/sec
total size is 817021756  speedup is 1.00

real12m39.031s
user0m4.689s
sys0m3.343s

## 2nd from EFS to local FS
sent 817004385 bytes  received 57108 bytes  28,668,824.32 bytes/sec
total size is 816703616  speedup is 1.00

real0m28.086s
user0m4.379s
sys0m2.865s

## 3rd from EFS to hosted NFS (in the same AZ, an EC2 hosted NFS)
time rsync -a -v -r /mnt/efsnfs/ /mnt/ec2nfs/
sent 817320922 bytes  received 57187 bytes  8,383,365.22 bytes/sec
total size is 817016294  speedup is 1.00

real1m36.785s
user0m4.616s
sys0m5.068s

**Comment by kahing** [comment]
Could you try `time rsync --inplace --size-only -a -v -r <src> <dest>`. Alternatively you can replace `--size-only` with `--modify-window=NUM` because S3 does not allow an explicit modification time. Note that `-a` mostly doesn't do anything because goofys does not fake ownership/group/permission and does not support symlink.

Using `--no-implicit-dir` (goofys option, not rsync) would also improve performance for initial rsync. Also consider disable both `--debug_s3` and `--debug_fuse` as they both slow things down.

**Comment by kahing** [comment]
another thing that can be done to speed up subsequent rsync is run find first:

```
$ find /mnt/S3dev/ > /dev/null
time rsync --inplace --size-only -vrWO /mnt/efsnfs/ /mnt/S3dev/
```

That's because find does `readdir` which would populate the stats cache faster than rsync (which does individual lstat). Depends on the amount of files you have you may want to increase `--stat-cache-ttl` and `--type-cache-ttl`

closing for now, reopen if you think there's something that goofys need to change
