### ISSUE TITLE
Reduce bandwidth/performance cost of tempfile-create-and-rename pattern

### ISSUE THREAD

**Issue by charles-dyfis-net** [kahing/goofys#274]
A user of goofys (@limbo127) recently filed folbricht/desync#9, asking that that program have support for directly creating output files rather than following the standard create-and-rename pattern which is appropriate to ensure that partial content is never created or written on POSIX filesystems (and which is widely used by common tools -- `sed -i`, `vim` with `backupcopy no`, `rsync` without `--inplace`, etc).

As this feature would be exclusively useful to users of filesystems similar to goofys, I'm inclined to suggest trying to fix this on the filesystem end. A few options come to mind:

- Implement server-side copy, akin to the similar feature in s3fs
- Provide the user to specify a pattern (such as `.*`) for files not to be uploaded; thus, a file would be locally cached -- perhaps in an unlinked inode on the local `/tmp` partition to ensure cleanup eventually occurs? -- until renamed, and only uploaded when that rename takes place.

Thoughts?

**Comment by kahing** [comment]
goofys already uses server side copy for rename. It doesn't buffer locally to disk before uploading so the second point is not possible to implement.

**Comment by kahing** [comment]
To add to my previous comment, although goofys does use server side copy, depends on the chunk sizes that desync uses this can still take significant amount of time (since AWS S3 actually does a copy). For tiny chunk sizes copy is fast but the additional copy op still incurs latency. Having an `rsync --inplace` like option is ideal from goofys' standpoint.

That said, I've worked on a proprietary system that's similar (NetApp AltaVault's predecessor Riverbed Whitewater), and looking at https://github.com/systemd/casync gives me the feeling that file sizes are likely relatively small, and so using it directly on a goofys-like filesystem isn't likely to get you great performance. But then using chunks as files is sub-optimal anyway but I am not going to tell you how to implement your project here :-)
