### ISSUE TITLE
article comparing speed

### ISSUE THREAD

**Issue by cekvenich** [kahing/goofys#307]
https://medium.com/@ozeri/high-throughput-object-store-access-via-file-abstraction-177a14537593

Somehow they get different results.

**Comment by kahing** [comment]
The author never tested real world speed without on disk cache, and only tested by stubbing code out so it's not representative of real world performance.

goofys at the time did not have an on disk cache. goofys has since gained the ability to use an on disk cache through [catfs](https://github.com/kahing/catfs/).
