### ISSUE TITLE
Azure Blob Storage support

### ISSUE THREAD

**Issue by kacejot** [kahing/goofys#435]
I have seen azure backend in the code and I have tried to use it.
I have passed wasd:// scheme to my account. 
Also I put account and key ~/.azure/config and created azureProfile.json by logging with az util on my system.

I have the next error messages:
```
2019/07/03 14:47:04.299442 main.ERROR Unable to access 'myaccount.blob.core.windows.net': invalid argument
2019/07/03 14:47:04.299481 main.FATAL Mounting file system: Mount: initialization failed
```

Also I have this log:

```
2019/07/03 14:43:13.689305 adlv1.ERROR <nil>
```
Which is unnecessary and I think it should be removed.
What is the current progress of implementing AZBlob support?
Could also please describe the steps how to mount AZBlob storage, if it works?

Thanks

**Comment by kahing** [comment]
Can you try adding `--debug-s3`?

**Comment by kahing** [comment]
Also, the syntax is supposed to be `wasb://container`

**Comment by dougstarfish** [comment]
I'm a little bit perplexed about the setup here.

AWS has bucket, access_key and secret_access_key
Azure has account_key (which is more like a secret), account_name, and container. 
To access in azure it's https://$acct.blob.core.windows.net/$container

so, I'm *guessing* that you put something in for the access_key and access_key_secret in the ~/.aws/credentials, but maybe that's incorrect? Is it account for the access key? Do you put the wasb: syntax into the endpoint url?

It also looks like you export CLOUD=azblob to trigger some action parsing differences, but maybe that's only internal for testing.

**Comment by kahing** [comment]
You are correct that azure has account key, account name, and container. If you have azure cli setup, and `az storage blob list -c <container>` works, then you run:

```
$ goofys wasb://<container> mntpoint
```

Under the hood goofys lookup the account key and account name (and the account domain) from the same place azure cli does.

Alternatively, you can set `AZURE_STORAGE_ACCOUNT` and `AZURE_STORAGE_KEY` in the environment (just like azure cli), or also use `--endpoint` instead of having setting the storage account.

I know none of this is documented anywhere yet, it's one of the things I need to do before making another release

**Comment by kahing** [comment]
I've added instruction here: https://github.com/kahing/goofys/blob/master/README-azure.md 

hope that helps
