### ISSUE TITLE
Error: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by bateller** [kahing/goofys#97]
Tried to run goofys from command line and had this issue. Ideas?

```
# ./bin/goofys -f --region us-east-1 bucket-test /mnt/bucket-test/
2016/08/10 16:39:02.923064 s3.ERROR code=RequestError msg=send request failed, err=Head https://s3.amazonaws.com/bucket-test: x509: certificate signed by unknown authority

2016/08/10 16:39:03.259353 s3.INFO Unable to detect bucket region, staying at 'us-east-1'
2016/08/10 16:39:03.259374 s3.INFO Falling back to v2 signer
2016/08/10 16:39:03.574995 s3.ERROR code=RequestError msg=send request failed, err=Head https://s3.amazonaws.com/bucket-test: x509: certificate signed by unknown authority

2016/08/10 16:39:03.575021 main.ERROR Unable to access 'bucket-test': RequestError: send request failed
caused by: Head https://s3.amazonaws.com/bucket-test: x509: certificate signed by unknown authority
2016/08/10 16:39:03.575034 main.FATAL Mounting file system: Mount: initialization failed
```

Used yum to install golang:
> Package golang-1.5.1-0.el6.x86_64

CentOS 6.x:
```
 # uname -a
Linux server.example.com 2.6.32-642.3.1.el6.x86_64 #1 SMP Tue Jul 12 18:30:56 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by kahing** [comment]
Is the bucket name actually `bucket-test`? I correctly got a 403 when I tried to use goofys to access that bucket and didn't get a certificate problem. Do you have other proxies between you and S3?

**Comment by bateller** [comment]
No its a different bucket name. No proxies. EC2 instance running CentOS 5.x AMI at AWS us-east-1

**Comment by kahing** [comment]
I am not able to reproduce this problem with Centos 5.4 x6_64 HVM (ami-0053dd30). What happens if you do something like:

`curl -I https://s3.amazonaws.com/bucket-test`

**Comment by Gorra007** [comment]
Hi,
I have the same problem with a minio server at the endpoint.

[root@g-x1 ~]# `goofys -f --debug_fuse --profile tsm3 -o allow_other --endpoint https://minio3.local:9000/ testbucket1 /mnt/s3buckets/testbucket1/`

2020/04/16 15:09:11.053909 s3.ERROR Unable to access 'testbucket1': x509: certificate signed by unknown authority
2020/04/16 15:09:11.633835 s3.ERROR code=RequestError msg=send request failed, err=Head "https://minio3.local:9000/testbucket1/1i4nv8o25j52jkpm5g0dhs1cwfivxv9c": x509: certificate signed by unknown authority

2020/04/16 15:09:11.635984 main.ERROR Unable to access 'testbucket1': RequestError: send request failed
caused by: Head "https://minio3.local:9000/testbucket1/1i4nv8o25j52jkpm5g0dhs1cwfivxv9c": x509: certificate signed by unknown authority
2020/04/16 15:09:11.637896 main.FATAL Mounting file system: Mount: initialization failed


**Server side:**
[root@minio3 ~]# `ls -l /home/sp3/.minio/certs/CAs/`
total 0
